### ISSUE TITLE
wrong kit contents or wrong schematic?

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious/MultiGeiger#11]
The schematic says:

- C2 10nF
- C4 100pF

My kit contains:

2x WIMA 100/1000 (red 5mm raster foil capacitor, "2,5" printed on the back)

So, what's correct?

**Comment by rexfue** [comment]
Also related to wrong (old) PCB version. Sorry for that.

**Comment by ThomasWaldmann** [comment]
OK, keep issue open for a while in case someone else also has old PCB.

**Comment by ThomasWaldmann** [comment]
Closing, there were only 3 of these boards and their location is known.

**Comment by ThomasWaldmann** [comment]
I still think there is an issue.

If you look there, you do not see any 2 capacitors with same value.

So, was my kit contents wrong? Only mine?

**Comment by rexfue** [comment]
The Kit-Content is wrong (blame Jürgen :-)  ). Tjalf had the same issue I guess: C2 was missing at his kit.

**Comment by ThomasWaldmann** [comment]
OK, guess the inital kit assembling is done by now (and the last kits I received didn't have this issue, so I guess this was a singular mistake). Closing.
