### ISSUE TITLE
PCB: adjust pin distance for D4 to 12.5mm

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious/MultiGeiger#12]
D4 BYV26E (glass) seems to have already 90deg bent wires fitting into 12.5mm raster.

The PCB v1.1 jb/rxf has 10mm raster, so one needs to re-adjust the diode wires to that raster.
Consider the diode is glass package, one needs to be careful not to damage it.

Would be better if the PCB fitted to default BYV26E raster of 12.5mm.

PCB v1.1 jb/rxf 2019-06

**Comment by rexfue** [comment]
Related to wrong PCB - first test version. Version 1.4 is the actual version.

**Comment by ThomasWaldmann** [comment]
Workaround: Can be re-bent using some pliers, be careful, glass!

**Comment by ThomasWaldmann** [comment]
Juergen said the diodes usually have straight wires, just these were already bent for some reason.

So this is not a general issue, closing.
