### ISSUE TITLE
Frage: Sind alternative Geigerzählrohre möglich?

### ISSUE THREAD

**Issue by Nordrunner01** [ecocurious/MultiGeiger#125]
Moin.

Besteht die Möglichkeit andere Zählrohre zu verwenden, beispielsweise SBM-20 und entsprechende korrekturfaktoren in der Firmware anzugeben?

Gruß

**Comment by rexfue** [comment]
Ja, in der Software sind SBM-20, SBM-19 und Si22G (unser 'Standard') vorgesehen und die Umrechnungsfaktoren hinterlegt.

**Comment by ThomasWaldmann** [comment]
See #14.
