### ISSUE TITLE
Frage: Ist es möglich das Geigerzählerrohr abzusetzen?

### ISSUE THREAD

**Issue by Nordrunner01** [ecocurious/MultiGeiger#126]
Moin.

Für eine mögliche andere Postion am Gehäuse. Ist es möglich das Zählrohr ein wenig von der Platine abzusetzen? Es geht dabei um wenige mm/cm.

Gruß

**Comment by rexfue** [comment]
Ich denke, da spricht nix dagegen.

**Comment by ThomasWaldmann** [comment]
Ein Kabel (`Tube -` ) ist ja eh anzulöten, das andere kann man genauso handhaben.

Bei `Tube +` eben beachten, dass das 400V sind, also nirgendwo damit in Kontakt oder auch nur in die direkte Nähe kommen.
