### ISSUE TITLE
PCB version mismatch

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious/MultiGeiger#13]
Seems I got a PCB v1.1 jb/rxf 2019-06 and it does not match the schematics v1.4 in this repo.

So, where do I find correct schematics and parts list?

**Comment by rexfue** [comment]
Sorry, Version 1.1 was the first test version an should not be used

**Comment by ThomasWaldmann** [comment]
Oh, guess we leave the issue open for a while in case someone else also got an old PCB.

In case there are instructions how to fix the old PCB, they could be linked from here.

**Comment by ThomasWaldmann** [comment]
Closing, there were only 3 of these boards and their location is known.
