### ISSUE TITLE
duplicated changelog

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious/MultiGeiger#141]
there is changelog information in:
- changelog.md
- multigeiger/version.h

One should be removed, it is not needed to have that at 2 places and only creates inconsistencies.
We already have them, not all versions are listed in both files.

**Comment by ThomasWaldmann** [comment]
@rexfue ^^^

**Comment by rexfue** [comment]
which one would you prefer?

**Comment by ThomasWaldmann** [comment]
changelog.md in toplevel dir is better visible, so users can easier find and read it.

**Comment by ThomasWaldmann** [comment]
please first merge my new OTA PR or it'll conflict as it updates version.h changelog.

**Comment by ThomasWaldmann** [comment]
did it already. it works, i tested it.

**Comment by rexfue** [comment]
Fine that it works.
keep changelog.md: OK. VERSION.MAJOR etc. still will be defined in version.h  without comments - OK?

**Comment by ThomasWaldmann** [comment]
Yes.

**Comment by ThomasWaldmann** [comment]
OK, I'll work on this later today.

**Comment by rexfue** [comment]
I think it would be better to delete version.h completely  and write the #define VERSION_MAJOR etc. directly into multigeiger.ino

**Comment by ThomasWaldmann** [comment]
ok.
