### ISSUE TITLE
duplication of IotWebConf into our codebase

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious/MultiGeiger#143]
Seems like we have a full copy of that.

Problems:
- the lib version is unknown (at least I could not find it anywhere)
- hard to update
- it is locally modified to add setThingName functionality

Maybe the modification could be done in a cleaner way by subclassing and extending that way?
If so, we could remove the lib code from git and just install it via arduino library manager, as usual.

**Comment by rexfue** [comment]
yea, sounds like a good idea. Could you please do it.

**Comment by ThomasWaldmann** [comment]
removed from milestone, see PR #146 and the ticket at IotWebConf project linked from there.
