### ISSUE TITLE
[Webseite] Linkkorrektur

### ISSUE THREAD

**Issue by Wikinaut** [ecocurious/MultiGeiger#149]
Auf https://ecocurious.de/projekte/multigeiger-2/ ist der Link zu korrigieren:

anstelle von 

* https://github.com/ecocurious/MultiGeiger/blob/Diskussion_Geigerprojekt/Diskussionsgrundlage

schlage ich 
* https://github.com/ecocurious/MultiGeiger *und*
* https://github.com/ecocurious/MultiGeiger/tree/master/docs/Bauanleitung (oder direkt das PDF, ohne Datum im Dateinamen, aber mit Datum/Versionsangabe im Text vor)

vor.

**Comment by rexfue** [comment]
@ecocurious Bitte den Link anpassen

**Comment by ecocurious** [comment]
Done!

**Comment by rexfue** [comment]
closed #149
