### ISSUE TITLE
lmic.h not found

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious/MultiGeiger#17]
If one has LoRa enabled in userdefines.h, it misses that header file.

searching for `lmic` in the arduino library manager yields 3 different libraries, which one is it and what's a known-good version of it?

This should be mentioned in `README.md`.

**Comment by rexfue** [comment]
OK, i will mention this.

**Comment by ThomasWaldmann** [comment]
Hmm, I just found a bundled `lmic.h` in `lib/MCCI_LoRaWAN_LMIC_library/src/`.

**Comment by ThomasWaldmann** [comment]
some comment about this is being added in PR #30.

**Comment by ThomasWaldmann** [comment]
`lib/MCCI_LoRaWAN_LMIC_library/src/` is that used or can it be removed?

People can add libs via library manager in arduino, right?

**Comment by rexfue** [comment]
Yes, you’re right. You can remove it.

**Comment by ThomasWaldmann** [comment]
OK, thanks for clarifying!
