### ISSUE TITLE
setup UI: clarify field names

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious/MultiGeiger#18]
The field names in the setup menu are all else than clear / self explaining:
```
Current         ---->      Suggested
Thing Name                 Built-in WiFi AccessPoint ESSID (do not change)
AP password                Built-in WiFi AccessPoint Password
WiFi SSID                  WiFi Client ESSID
WiFi passwort              WiFi Client Password
```

If named like that, I guess the docs could be shortened as it is self-explaining.

**Comment by rexfue** [comment]
I want to change the GUI anyway. We need to have some settings from userdefines.h to be available in the web interface (i.e. speaker on/off etc).

**Comment by ThomasWaldmann** [comment]
As a first step, would the field names as suggested be ok?

**Comment by ThomasWaldmann** [comment]
ping?

**Comment by rexfue** [comment]
I suggest shorter names
Thing Name                 Geiger-SSID
AP password                Geiger-Password
WiFi SSID                    Home-WLAN SSID
WiFi passwort             Home-WLAN Password

I won't use 'WiFi', because in every (German) mobile phone there it's called WLAN.

**Comment by ThomasWaldmann** [comment]
The first 2 are one set of credentials and belong together, so that should be reflected in the field name by using the same wording (except ssid and password, which is the only difference).

Same for the last 2.

Not sure why we need to talk about "thing" (there is TTN for LoRa, but we are talking about wifi stuff here).

**Comment by ThomasWaldmann** [comment]
And in general I would just write it in a way so one does not need to read docs to understand it.

**Comment by ThomasWaldmann** [comment]
I would not talk about "Home WLAN" or "Home WiFi".

If i install one at my company, it is not my "home".

AFAIK, WLAN is the more popular term in german speaking countries, while WiFi is the usual english term.

**Comment by rexfue** [comment]
Explanation:
The names came from the third party library IotWebConf and I wouldn’t change there anything in the first place.

**Comment by ThomasWaldmann** [comment]
I assumed the names of the fields are configurable? Didn't look at the code yet.

Also I think we already agreed to use English consistently and not half English, half German?

**Comment by rexfue** [comment]
> On 18. Nov 2019, at 11:43, TW <notifications@github.com> wrote:
> 
> I assumed the names of the fields are configurable? Didn't look at the code yet.
> 
> 
Don’t know, may be.

> Also I think we already agreed to use English consistently and not half English, half German?
> 
> 
And what is with WLAN not english?

**Comment by ThomasWaldmann** [comment]
My mobile phone (en-US) says "Wi-Fi" in the settings (so guess I am right that this is the more usual term in English).

**Comment by rexfue** [comment]
But WLAN is an english abbreviation

**Comment by ThomasWaldmann** [comment]
yes. "Handy" also sounds english, but only used by german speaking people while english speaking ones say "mobile" or "mobile phone".

**Comment by ThomasWaldmann** [comment]
https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/w/wi-fi

(they do not address Wi-Fi vs. WLAN there)

**Comment by ThomasWaldmann** [comment]
Opinion from IRC:
```
11:57  elho$ 
Not a native speaker, but its not wlan (that's more a German thing, like "Handy" for mobile).

Wikipedia uses Wi-Fi and states: The name is sometimes written as WiFi, Wifi, or wifi, but these are not approved by the Wi-Fi Alliance. IEEE is a separate, but related, organization and their website has stated "WiFi is a short name for Wireless Fidelity".
```

**Comment by rexfue** [comment]
OK, I don't want to decide it. Lets here the others too.

I guess, our normal user is german (most of them) and - referring to Nicola - he should not be a 'technician'. So I prefer WLAN.

**Comment by ThomasWaldmann** [comment]
@rexfue I totally misunderstood your comment where you suggested names due to the missing formatting. I thought you just suggested the new names, but guess you meant `old new`.

I added some `-->` to make it clearer as `old --> new`.

**Comment by ThomasWaldmann** [comment]
As a general note, `-` (Bindestrich) is also rather a german thing. In English it is often just a blank.
