### ISSUE TITLE
remove pointless comments

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious/MultiGeiger#27]
In the source, there are quite some not really needed comments (while needed comments are missing at other places).

If the comment text just repeats what's already clearly seen in the code, I would suggest removing it as it is just a burden and not useful.

Examples:
```
isr_GMZ_counts++;  // Count

GMZ_counts = isr_GMZ_counts;  // copy values from ISR 

u8x8.setFont(u8x8_font_5x8_f);     // small size

clearDisplayLine(7);                    // clear line

u8x8.drawString(0, 7, txt.c_str());     // print it

cycle_time_us   = 1000000000/frequency_mHz;       // calculate all we need

int httpResponseCode = http.POST(body);                   //Send the actual POST request
String response = http.getString();                       //Get the response to the request
Serial.println(httpResponseCode);   //Print return code
Serial.println(response);           //Print request answer

...
```

**Comment by rexfue** [comment]
It's more burden to delete them than let them in! They don't bother me.

**Comment by ThomasWaldmann** [comment]
I can delete them if we agree they are pointless and could be deleted.

**Comment by rexfue** [comment]
ok

**Comment by ThomasWaldmann** [comment]
BTW, I will be in shackspace tomorrow afternoon (~ after 14:00) and try to get the geigers assembled and running. Maybe some other guy from Neckarwestheim will join me and assemble one of them.

**Comment by rexfue** [comment]
Viel Spaß und viel Erfolg!

Von meinem iPad gesendet

**Comment by ThomasWaldmann** [comment]
Doing this now.
