### ISSUE TITLE
global variables with 1 char name: t, h, p

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious/MultiGeiger#29]
Not good style and can't be searched for easily.

**Comment by ThomasWaldmann** [comment]
```
      t = bme.readTemperature();
      h = bme.readHumidity();
      p = bme.readPressure();
```

So, rename them to temperature, humidity, pressure?

**Comment by ThomasWaldmann** [comment]
there is change relating to this in PR #30.

**Comment by rexfue** [comment]
shall I close this (and other solved) issue(s)  or will you do it?

**Comment by ThomasWaldmann** [comment]
I can do it after it is in master.

I a commit specifically fixes some github issue, one can also write a commit comment like:
```
some comment that makes sense, fixes #123
```
Then github will auto-close the issue when the PR is merged into master.

**Comment by rexfue** [comment]
OK understood

**Comment by ThomasWaldmann** [comment]
was merged, so this is fixed.
