### ISSUE TITLE
language?

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious/MultiGeiger#3]
the project seems to be a bit undecided whether it should be in English or German, leading to a mix of both in misc. places:

- source code
- user interface
- docs

**Comment by rexfue** [comment]
You are right.
I think, docs should be preferably in german because we want also lay persons to build the device.
Source could (should) be in english, only developers would read it ('profis' :-) )
What do you mean with 'user interface' ?

**Comment by ThomasWaldmann** [comment]
Actually, I guess the german strings I have seen in the src are for serial (usb) log output.

**Comment by ThomasWaldmann** [comment]
In the src, there is quite frequently the GMZ (Geiger-Mueller-Zaehler/Zaehlrohr) abbreviation mixed with english words - this is a rather unpretty.

Better:
- leave it away as we only deal with pulses of that anyway?
- GMC (counter)
- GMT (tube)

**Comment by ThomasWaldmann** [comment]
Some of the inconsistencies are fixed by PR #28, but not the GMZ stuff.

**Comment by ThomasWaldmann** [comment]
Any comment to my suggestions?

**Comment by rexfue** [comment]
I would prefer GMC.  (GMT ist a time zone for me).

**Comment by ThomasWaldmann** [comment]
@WwwBoehriDe GMC fine for you, too or do you prefer sth else?
