### ISSUE TITLE
git: tags for releases are missing

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious/MultiGeiger#31]
On github, if you click on "Code" -> "Branch" -> "Tags", you see there is only one tag define yet.

Guess there should be a tag for everything that is mentioned as a separate version in the change log.

**Comment by ThomasWaldmann** [comment]
btw, to not forget such stuff, it is a good practice to have some "how to make a release" in the developer docs of a project.

this also would help making a release in case the person normally doing it has no time to do it.

**Comment by rexfue** [comment]
OK, tags are missing. In future we will add tags.

**Comment by ThomasWaldmann** [comment]
1.9 tag also missing.

**Comment by rexfue** [comment]
Shit, i knew, i will forget something.

**Comment by ThomasWaldmann** [comment]
see #46.

not sure if it is important to have tags for past / current releases?

if so, keep this open. otherwise, we can close this ticket.
