### ISSUE TITLE
use other pins to not need external pullup resistors?

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious/MultiGeiger#32]
From the ESP32 docs:
```
GPIO34-39 can only be set as input mode and do not have
software pullup or pulldown functions.
```

That's were PCB 1.4 has the dip switches and the external 10k pullup resistors.

If we could use some other pins, we could use internal (sw configurable) pullups and no need to buy / solder / have PCB space for 4 resistors.

**Comment by ThomasWaldmann** [comment]
https://esp32.com/viewtopic.php?t=5111

Internal: about 50kOhm (between 10k and 100k).

**Comment by ThomasWaldmann** [comment]
When considering what the lora heltec device uses for other purposes, these GPIOs seem still completely unused:

1 io
3 io
13 io
17 io
32 i
33 i

**Comment by rexfue** [comment]
OK, good idea. But wrong!

We want to use 3 Chips: Heltec Wifi Kit 32, Heltec Wireless Stick and Heltec Wireless Stick lite.
And among these 3 there is NO Pin free (see attached Excel sheet).

**Comment by rexfue** [comment]
Ups sorry, missed the Excel file.

**Comment by ThomasWaldmann** [comment]
OK, I only looked at the Heltec Wifi and Wifi/Lora uC boards.

**Comment by ThomasWaldmann** [comment]
Still would be interested in the spreadsheet. :-)

**Comment by rexfue** [comment]
BTW: the switch is only optional- That means, the average user has no need to solder / buy  the the switch and the resitsiors.

**Comment by rexfue** [comment]
should be on the way (sent 22:33)

**Comment by ThomasWaldmann** [comment]
Link:

https://github.com/ecocurious/MultiGeiger/blob/master/docs/hardware/Pinning_of_HeltecBoards.pdf
