### ISSUE TITLE
parts list missing

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious/MultiGeiger#33]
in the docs directory, there is:
- the pcb
- the schematic

A parts list is missing (needed to check kit contents or to order parts).

**Comment by ThomasWaldmann** [comment]
@rexfue @WwwBoehriDe can the parts list get "exported" from the tools you use?

Shall I make one manually?

**Comment by WwwBoehriDe** [comment]
Hi, I will modify it today and (try to  :-)  )load it up. Is an EXCEL-File OK for you? Or what would be best? Lirbre Office?

**Comment by ThomasWaldmann** [comment]
Libre Office Calc (not $$$) or just a .txt file?

**Comment by ThomasWaldmann** [comment]
fixed by https://github.com/ecocurious/MultiGeiger/commit/85f00aa2347704311a175925df147da6e302b007
