### ISSUE TITLE
random reboots?

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious/MultiGeiger#39]
I've seen the geigers playing the startup sound multiple times after plugging into USB.

Random reboots? Fatal exceptions leading to reboots? Power? HV issues?

**Comment by rexfue** [comment]
Don't know what causes that, haven't seen it yet.

**Comment by ThomasWaldmann** [comment]
Have it seen today again, had the MultiGeiger running for some hours and it rebooted multiple times (noticeable due to the startup sound).

Was indoors at room temperature, located without case on a table (plastic surface).

**Comment by ThomasWaldmann** [comment]
Note: always have a look at serial/usb output when such stuff happens.

Also had reboots today, see #82 - as @rexfue is already working on the ISR stuff, I am closing this for now.
