### ISSUE TITLE
milestones

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious/MultiGeiger#47]
there is a nice feature on github, called milestones.

they can be used for release planning ("what shall get into next release?") by assigning tickets to milestones.

if all tickets in a milestone are closed (or it has been decided to remove them from that milestone), the code is release-ready.

so, what's the next release? 1.10?

**Comment by rexfue** [comment]
I think, all these pretty nice tools and possibilities are a little overkill for our little geiger counter.

Yes, I think we call it 1.10.

**Comment by ThomasWaldmann** [comment]
The point about milestone is to make goals documented.
If multiple people work on a project, it is good if everybody knows the goals for release x.
So they know what to do / what not to do / what to do later and can help.

Also, one will notice when the goal is reached and stuff is release-ready.

**Comment by ThomasWaldmann** [comment]
As we might have an assembly at 36c3, I added a milestone for stuff that should be done until then.

**Comment by ThomasWaldmann** [comment]
milestones are also covered in #56, so this issue can be closed.
