### ISSUE TITLE
Is Heltec WiFi Kit 32 (V3) supported?

### ISSUE THREAD

**Issue by Nestade** [ecocurious/MultiGeiger#473]
Hello,

I just attempted to set up my current MultiGeiger with WiFi to integrate it into the measuring network. Unfortunately, it appears that the WiFi on my Heltec WiFi Kit 32 is not functioning properly, so I may need to get a new one. Does anyone know if I can use the Heltec WiFi Kit 32 (V3), or does it have to be the previous revision?

Regards,
Nestade

**Comment by rexfue** [comment]
No, sorry, V3 ist still not supported. You can get a V2-Board from Jürgen ( juergen@boehri.de ). Regards Reinhard

**Comment by Nestade** [comment]
Thanks for the quick reply. I unexpectedly found the issue when I touched the PCB antenna, and it suddenly connected. I'll solder an external antenna to see if that resolves the issue. 

EDIT: An external antenna fixed it.
