### ISSUE TITLE
comments -> userdefines(-example).h

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious/MultiGeiger#51]
Instead of having the long description of the options in userdefines.h in the README.md, I guess these comments/explanations should be put directly into userdefines.h.

In the README, we then just need to say "to configure, read / edit there" and we're done.
Also, stuff stays better in-sync, e.g. if defaults change, names change, etc.

**Comment by rexfue** [comment]
OK, good point.

**Comment by ThomasWaldmann** [comment]
Doing that now.
