### ISSUE TITLE
MESSINTERVALL bug?

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious/MultiGeiger#6]
https://github.com/ecocurious/MultiGeiger/blob/master/multigeiger/multigeiger.ino#L147

should that be 600? see comment above it.

**Comment by rexfue** [comment]
Now we use 2.5 min, so it should be 150 and comment should be changed. Will be corrected in next version

**Comment by ThomasWaldmann** [comment]
For now, I just fixed the language and the consistency, so it is MEASUREMENT_INTERVAL and still 60 now + a fixed comment, see PR #28.

The actual code behaviour change still needs to be done.

**Comment by ThomasWaldmann** [comment]
Was recently fixed, closing.
