### ISSUE TITLE
README: fix intro section

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious/MultiGeiger#65]
the intro section of the README could be improved / rewritten, typos and grammar fixed.

this was already done once, but reverted on nicola's request (#64), so it is her job now to do that.

**Comment by ThomasWaldmann** [comment]
@ecocurious (nicola) do you want to fix that before the workshop?

**Comment by ecocurious** [comment]
was denn? ich finds nicht. bin

**Comment by ThomasWaldmann** [comment]
einfach das github ticket lesen (siehe top post dort/hier und der link darin).

**Comment by ecocurious** [comment]
ja aber auf was konkret der sich bezieht ist dann nicht klar. 

bin krank und werde die nächsten tage nix machen

**Comment by ThomasWaldmann** [comment]
wenn du auf den link draufklickst, wird es sehr konkret.

**Comment by ecocurious** [comment]
eben nicht, ich soll was fixen aber was genau, ist nicht klar. 
worum gehts genau, kannst du mir das kurz nennen? 

sorry ich bin krank, wenn es nicht wichtig ist bleibts halt so.

**Comment by ThomasWaldmann** [comment]
bitte fixe es, wenn du wieder gesund bist. es steht alles da oben.

**Comment by ecocurious** [comment]
der screenshot sagt, alles ok
und du weigerst dich zu sagen worum es geht

gute nacht

**Comment by ThomasWaldmann** [comment]
OK, typos fixed.
