### ISSUE TITLE
isr_GMC_counts lost

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious/MultiGeiger#70]
In the main loop:
- it first copies the value of `isr_GMC_counts`
- then does **misc. stuff** that takes considerable time and
- then it assigns `isr_GMC_counts = 0`.

In the background, `isr_GMC_counts` is incremented by interrupts from the GM tube.

All increments / counts that happened while the main loop did **misc. stuff** are lost.

**Comment by rexfue** [comment]
You are right, that could lead to a missing pulse. Bad programming, should be changed.
But how fast must the pulse rate be to miss a pulse? In practice, this will not happen.

**Comment by ThomasWaldmann** [comment]
If the pulse rate is low (small tube and/or low radiation), it will likely miss only few pulses.

The **misc stuff** takes at least 4ms (just for speaker/led tick, not sure how much the web and other stuff adds to this), it will just miss all pulses that happen in that time.

**Comment by ThomasWaldmann** [comment]
@rexfue close?

btw, you can close tickets automatically by appending ", fixes #XXX" to the commit comment of the fix. github then will close the ticket as soon as the changeset is merged into master.

**Comment by ThomasWaldmann** [comment]
guess this is fixed by a recent PR.
