### ISSUE TITLE
log output gets mixed up

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious/MultiGeiger#85]
if one configures Serial_Logging or One_Minute_Log to output some tabular data, some other output gets in between the table rows:

- wifi init output from esp
- other output from multigeiger code

this should be either cleaned up (suppress other output) or tagged (so that one can filter the output one wants to see, e.g. with grep or other means).

**Comment by ThomasWaldmann** [comment]
Tagging could work like:
```
... (misc. esp32 output we can not influence)
GEIGER: <our output>
```

Then one could just filter for `^GEIGER:` to get *our* lines.

**Comment by ThomasWaldmann** [comment]
```
GEIGER: 
```

**Comment by rexfue** [comment]
Done. PR #160
