### ISSUE TITLE
PCB: holes for L1 are too narrow diameter

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious/MultiGeiger#9]
when trying to put L1 inductivity through the respective PCB holes, it does not fit, the holes are too narrow (or the wires of that L1 model are too thick).

L1: "154J" black, ferrite.
PCB v1.1 jb/rxf 2019-06

**Comment by ThomasWaldmann** [comment]
Workaround: use a sharp cutter knife to thinnen the wires a bit.

**Comment by rexfue** [comment]
Also related to wrong (old) PCB version. Sorry for that.

**Comment by ThomasWaldmann** [comment]
OK, keep issue open for a while in case someone else also has old PCB.

**Comment by ThomasWaldmann** [comment]
Closing, there were only 3 of these boards and their location is known.
