### ISSUE TITLE
lots of millis() calls

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious/MultiGeiger#91]
there are quite a lot of them.

for many CPUs, a subroutine call is rather expensive, so guess we could do something like:

```
ms = millis();  // once
foo = ms;
...  // assuming this is all relatively quick stuff
bar = ms;
```

**Comment by ThomasWaldmann** [comment]
`ms` or `now_ms` or `t_ms`?

**Comment by rexfue** [comment]
We could change that. But this is a real fast CPU, so the impact on speed is not really significant. I think the only important place are the two call in the ISR. I will do the changes in the next PR.
