### ISSUE TITLE
speaker / led tick not working any more

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious/MultiGeiger#97]
with current master branch: no ticks, no flashing.

cpm display seems to work though.

**Comment by ThomasWaldmann** [comment]
50839d008db253d3b1d55e3c9f7b2a1e27f2035c works
377db2a59d9f45ab155a64c2d7cc7b132e597d22 does not work

bisecting this now ...

**Comment by ThomasWaldmann** [comment]
git bisect tells this:
```
b9bb9bc5423bb28500f56e9dd736c133e044411c is the first bad commit
commit b9bb9bc5423bb28500f56e9dd736c133e044411c
Author: Reinhard X. Fürst <rexfue@gmail.com>
Date:   Tue Nov 19 16:16:03 2019 +0100

    isr routines now esp32 conform
    removed all "nointerrupt()/interrupt()"
    fixed a few global variables
    changed char variables to int

:040000 040000 128d05f015e1df93ae5ece922024ed7683d5a3ee fbe842465ff0a6e60b28b193b6f42e1368ea5fa7 M	multigeiger
```

**Comment by rexfue** [comment]
Was bedeutet das? Was ist bisect?

**Comment by ThomasWaldmann** [comment]
automatisiertes finden des commits, ab dem es nicht mehr tut. macht intern ne binaere suche, d.h. selbst bei 1000 commits hat man den "schlechten" nach 10 versuchen.

**Comment by rexfue** [comment]
Ah, OK, danke. Kann Du da weiter suchen? Ich komm da grad nicht dazu.

**Comment by rexfue** [comment]
What about the switch? SW1 = OFF(1) disables the speaker tick.

**Comment by ThomasWaldmann** [comment]
I don't have switches on this geiger. Also userdefines.h is correct and it does tick with an old sw version, just not with latest one.

Yeah, I have some time, will work on this.

**Comment by rexfue** [comment]
OK thanks.
